### ISSUE TITLE
Support auth of ES?

### ISSUE THREAD

**Issue by Widerstehen** [onesuper/pandasticsearch#22]
How to join auth of ES to pandasticsearch ?

DataFrame.from_es(url='http://local:9200', index='people')

I has tried following
DataFrame.from_es(url='http://user:passwd@local:9200', index='people')

but i get error 
pandasticsearch. u'WWW-Authenticate': u'Basic realm="secu…………

**Comment by onesuper** [comment]
Authentication is implemented (#23  @jjensn) and released in 0.5.0
