### ISSUE TITLE
dataframe limitation

### ISSUE THREAD

**Issue by cristiano74** [onesuper/pandasticsearch#25]
Hi, that is a great code! And I have this ES version : '6.2.3'
But when I use Dataframe API I see just 20 rows as result, even if the resultset is wider, where I wrong here?

```
from pandasticsearch import DataFrame
from pandasticsearch.client import RestClient
df = DataFrame(client=RestClient('https://.../_search',), index='indexname')
results=df.to_pandas()
```
Any suggestions would be really apprecited

**Comment by onesuper** [comment]
By default, a DataFrame will fetch only 20 rows from ES server unless a limiter is used:

`
results = df.limit(100).to_pandas()
`

**Comment by arthur-rocha** [comment]
Hi. Congrats for the nice work! 
So, when I need more than, let's say 10000 rows, my ES server starts to crash.
What I need to know is if pandasticsearch supports pagination for these cases, that is, it can load the data in batches and bind them later.

**Comment by onesuper** [comment]
Pagination will be discussed in this issue :https://github.com/onesuper/pandasticsearch/issues/6

**Comment by onesuper** [comment]
https://github.com/onesuper/pandasticsearch/issues/6 is closed now! @arthur-rocha

**Comment by pedro93** [comment]
@onesuper Do you have an example on how to pull more than 10k rows?
