### ISSUE TITLE
ImportError: No module named operators

### ISSUE THREAD

**Issue by xixici** [onesuper/pandasticsearch#27]
When I try pip install pandasticsearch. It occurs wrong like 
```
from pandasticsearch import DataFrame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda2\lib\site-packages\pandasticsearch\__init__.py", line 3, in <module>
    from pandasticsearch.dataframe import DataFrame, Column
  File "D:\Anaconda2\lib\site-packages\pandasticsearch\dataframe.py", line 5, in <module>
    from pandasticsearch.operators import *
ImportError: No module named operators
```

So, I try to use the version 
```
pip install pandasticsearch==0.4.0
Collecting pandasticsearch==0.4.0
  Could not find a version that satisfies the requirement pandasticsearch==0.4.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.4.3, 0.5.0)
No matching distribution found for pandasticsearch==0.4.0
You are using pip version 9.0.3, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
Then use
```
pip install pandasticsearch==0.4.3
```

This problem has been solved .

**Comment by statmatt** [comment]
Seconded. 
`import pandasticsearch` 
gives 
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-3c718573a7fd> in <module>
----> 1 import pandasticsearch

/opt/conda/lib/python3.6/site-packages/pandasticsearch/__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from pandasticsearch.dataframe import DataFrame, Column
      4 from pandasticsearch.client import RestClient
      5 from pandasticsearch.queries import Select, Agg

/opt/conda/lib/python3.6/site-packages/pandasticsearch/dataframe.py in <module>
      3 from pandasticsearch.client import RestClient
      4 from pandasticsearch.queries import Agg, Select
----> 5 from pandasticsearch.operators import *
      6 from pandasticsearch.types import Column, Row
      7 from pandasticsearch.errors import DataFrameException

ModuleNotFoundError: No module named 'pandasticsearch.operators'`

**Comment by statmatt** [comment]
this is probably due to, in your module `__init__.py` you have 
```
from pandasticsearch.client import RestClient
from pandasticsearch.queries import Agg, Select
from pandasticsearch.types import Column, Row
from pandasticsearch.errors import DataFrameException
```
which never calls the offending line `from pandasticsearch.operators import *` so passes the build step, and you have now operators as a submodule with its own `__init__.py` but forgot to correctly change the reference in `dataframe.py`

**Comment by CheungChan** [comment]
+1

**Comment by onesuper** [comment]
Problem is revolved in v0.5.1
