### ISSUE TITLE
DataFrameException for a ES7 instance

### ISSUE THREAD

**Issue by ovz** [onesuper/pandasticsearch#36]
Hi,

Used the following docker commands to standup an ElasticSearch instance.

```
docker pull docker.elastic.co/elasticsearch/elasticsearch:7.3.1
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.3.1
```

When I tried to use pandasticsearch with it I got

`DataFrameException: Please specify mapping for ES version under 7`.

What is the best way to address this?

Here is the code I used

```
#%%
local_endpoint = 'http://127.0.0.1:9200'
local_index = 'test_index'
es = Elasticsearch(hosts=local_endpoint
                       , timeout=240)

es.indices.create(index=local_index, ignore=400)
es.index(index=local_index, doc_type='post', id=1, body={
  'author': 'John Doe',
  'blog': 'Learning Elasticsearch',
  'title': 'Using Python with Elasticsearch',
  'tags': ['python', 'elasticsearch', 'tips'],
})

es.get(index=local_index, doc_type='post', id='1')
#%%
from pandasticsearch import DataFrame

df = DataFrame.from_es(url=local_endpoint, 
                       index=local_index)
df.print_schema() 

This returns

```

---------------------------------------------------------------------------

DataFrameException                        Traceback (most recent call last)

<ipython-input-33-baf8b725ecdf> in <module>
      3 df = DataFrame.from_es(url=local_endpoint, 
      4                        index=local_index)
----> 5 df.print_schema()

~/miniconda3/envs/r4_da/lib/python3.7/site-packages/pandasticsearch/dataframe.py in print_schema(self)
    451                 sys.stdout.write(self.resolve_schema(json_obj))
    452             else:
--> 453                 raise DataFrameException('Please specify mapping for ES version under 7')
    454 
    455     def resolve_schema(self, json_prop, res_schema="", depth=1):

DataFrameException: Please specify mapping for ES version under 7
```

**Comment by onesuper** [comment]
You can try with specifying the doc_type(mapping) for ES version under 7, for example: 

```
df = DataFrame.from_es(url=local_endpoint, 
                       index=local_index, doc_type='abc')
```

**Comment by onesuper** [comment]
@ovz I have changed message of the exception to make it easy to understand

**Comment by ovz** [comment]
I've figured out after I added a print statement to `dataframe.py` that `doc_type='doc'` is the correct `doc_type` for my production ElasticSearch 6 index.

```
print(f'self._mapping[index_name]["mappings"] = {self._mapping[index_name]["mappings"]}')
                json_obj = self._mapping[index_name]["mappings"][self._doc_type]["properties"]

```

For ES7 one has to use `compat` to work around this

```
from pandasticsearch import DataFrame

df = DataFrame.from_es(url=local_endpoint, 
                       index=local_index,
                       compat=7, # No doc_type for ES7
                       )
df.print_schema() 
```
