### ISSUE TITLE
Planned support for scroll API?

### ISSUE THREAD

**Issue by arnaudsj** [onesuper/pandasticsearch#5]
Hi, I have been playing with pandasticsearch and I absolutely love the idea and the way you implemented it. Any plans to add a way to return a large amount of data from ES? I would like to use this to build a simple data export facility out of ES with built in filters and other goodies you made available already, but the right now I am getting this when attempting to collect a large amount of data back:

`ServerDefinedException: {'phase': 'query', 'reason': 'all shards failed', 'failed_shards': [{'shard': 0, 'reason': {'reason': 'Result window is too large, from + size must be less than or equal to: [10000] but was [100000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.', 'type': 'query_phase_execution_exception'}, 'node': 'KyF9hZtLTBe6xVblape6Lg', 'index': 'test'}], 'type': 'search_phase_execution_exception', 'root_cause': [{'reason': 'Result window is too large, from + size must be less than or equal to: [10000] but was [100000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.', 'type': 'query_phase_execution_exception'}], 'grouped': True}`

**Comment by onesuper** [comment]
Scoll/Scan API is a useful functionality. #6 is now on the roadmap. Thank you very much for proposing this idea!

**Comment by sany2k8** [comment]
Any update on scroll API?

**Comment by sychev-a-k** [comment]
Do you have a plan to realize scroll API in near feature, your library is great!)

**Comment by onesuper** [comment]
The scroll function is now supported and Pandasticsearch can load all your ES data to memory now
