### ISSUE TITLE
filter not working for ES 5.2.0

### ISSUE THREAD

**Issue by vijaypalmanit** [onesuper/pandasticsearch#7]
df.filter(df.age < 25).select('lastname', 'age').collect()

df.filter(df.age < 25).select('lastname', 'age').collect()
Traceback (most recent call last):

  File "<ipython-input-22-6c94684eaa18>", line 1, in <module>
    df.filter(df.age < 25).select('lastname', 'age').collect()

  File "C:\Users\vijay\Anaconda3\lib\site-packages\pandasticsearch\dataframe.py", line 306, in collect
    query = self._execute()

  File "C:\Users\vijay\Anaconda3\lib\site-packages\pandasticsearch\dataframe.py", line 289, in _execute
    res_dict = self._client.post(data=self._build_query())

  File "C:\Users\vijay\Anaconda3\lib\site-packages\pandasticsearch\client.py", line 102, in post
    raise ServerDefinedException(reason)

ServerDefinedException: {'root_cause': [{'col': 98, 'line': 1, 'reason': 'no [query] registered for [filtered]', 'type': 'parsing_exception'}], 'line': 1, 'reason': 'no [query] registered for [filtered]', 'type': 'parsing_exception', 'col': 98}

**Comment by onesuper** [comment]
vijay, I guess this error is related to the API version of Elasticsearch?  What's the version of Elasticsearch are you using?

**Comment by vijaypalmanit** [comment]
Hi,
First of all I would like to say many many thanks for your efforts in building this awesome package/library, and also for replying me on this issue.

```
 I am using ES 5.2.0
 and its "lucene_version" : "6.4.0"
```

**Comment by onesuper** [comment]
The "filtered" query is used in this library to construct filter API. But it has been deprecated and removed in ES 5.0.

**Comment by vijaypalmanit** [comment]
so what to do, and how to run the below queries:(if any alternate way)

`df.filter(df.age < 25).select('lastname', 'age').collect()`

**Comment by onesuper** [comment]
I am sorry that the filter can not work for ES > 5.0. @vijaypalmanit # #

**Comment by mmacny** [comment]
Hi @onesuper  Any update on this? Was unable to get it working with ES 5.5 so basically having to write one myself

**Comment by onesuper** [comment]
@mmacny In the latest version, ES 5.0 is supported. You could initialize a DataFrame by passing a 'compat' parameter, e.g.

```
df = DataFrame.from_es(url='http://localhost:9200', index='people', compat=5)
```
